name: Test and Deploy Coverage

on:
  push:
    branches: [development, master]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Deploy coverage report to GitHub Pages
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/test-coverage'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage
          branch: gh-pages
